modLoader="javafml"
loaderVersion="[36,)"
license="GPLv3"
[[mods]]
modId="petorbs"
version="${file.jarVersion}"
displayName="Pet Orbs"
displayURL="http://www.curseforge.com/minecraft/mc-mods/pet-orbs"
authors="IchHabeHunger54"
description='''
Adds in little pet orbs, that eat certain items to give you buffs or items while in your inventory.
'''
[[dependencies.petorbs]]
modId="forge"
versionRange="[36,)"
mandatory=true
ordering="NONE"
side="BOTH"
[[dependencies.petorbs]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"
